version = "3.11.1"
runner.dialect = scala3
maxColumn = 100
indent.main = 2
indent.callSite = 2
indent.defnSite = 2
newlines.topLevelStatementBlankLines = [{ blanks = 1 }]
docstrings.style = Asterisk
align.preset = none
trailingCommas = always
rewrite.rules = [PreferCurlyFors, SortImports, RedundantBraces]
rewrite.redundantBraces.maxBreaks = 10
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false
